### ISSUE TITLE
Send direct messages in HTML

### ISSUE THREAD

**Issue by Facyla** [ColdTrick/html_email_handler#21]
Currently HTML messages are sent in plain text, inside the template generated by html_email_handler, which is a bit frustrating.
It would be nice to have the messages/send action use a rewritten message_send function to avoid stripping tags when messages are sent via email.

I'm wondering if this should be handled by this plugin or elsewhere...

**Comment by juho-jaakkola** [comment]
I was going to add an issue for automatically converting URLs into links, but apparently this issue needs to be fixed first.

Best approach might be to modify Elgg core to allow skipping this part: https://github.com/Elgg/Elgg/blob/1.9/engine/lib/notification.php#L678

**Comment by juho-jaakkola** [comment]
In fact one option could be to use the ```[format, strip_tags]``` hook. In the parameters there's the key ```original_string``` that contains the string with all the original HTML tags.

**Comment by siteleas** [comment]
After extracting the zip to the mod folder and renaming the folder (removing -master) and activating the plugin, I received the following error.

Fatal error: require_once(): Failed opening required '/home/chetnetwork/public_html/mod/html_email_handler/vendor/autoload.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/chetnetwork/public_html/mod/html_email_handler/start.php on line 8

I had to manually remove the directory to resolve the issue. I was unable to get the mod working because of it. How do I resolve this problem? Also, will this plugin work in conjunction with the newsletter plugin?

**Comment by bruno-infotrad** [comment]
Another option could be to bypass _elgg_notify_user and use the notify:email hook to use the message object to generate the email (like what the site notification plugin is doing)

**Comment by jdalsem** [comment]
This has been fixed in the Elgg 4 core email features
